[package]
name = "grep_cli"
version = "0.1.0"
authors = ["Thammanoon Phattramarut <blackjester1412@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
